// Generated by BUCKLESCRIPT VERSION 4.0.5, PLEASE EDIT WITH CARE
'use strict';

var ReactDOMRe = require("reason-react/src/ReactDOMRe.js");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var Main$ReactTemplate = require("./Main.bs.js");

ReactDOMRe.renderToElementWithId(ReasonReact.element(undefined, undefined, Main$ReactTemplate.make(/* array */[])), "main");

/*  Not a pure module */
